### ISSUE TITLE
[ASK] Key Bindings emoticons

### ISSUE THREAD

**Issue by thenoobi** [mchorse/mchorse.github.io#3]
Im sory to post here, but I cant find place to post this questions.
How to asign/ create new key for emoticons? For now I only can play animations by using "O" key randomly 
Any Idea how to change to others keys?

Thanks before

**Comment by mchorse** [comment]
Hello, I've shown how to do this in [this video](https://www.youtube.com/watch?v=3UVXBNETquk).

**Comment by thenoobi** [comment]
thanks bro, I'm also subcribe to your chanel :D
