### ISSUE TITLE
[Emoticons Request] Stop/Change Animation When Pressing New Key

### ISSUE THREAD

**Issue by thenoobi** [mchorse/mchorse.github.io#4]
Hello again bro, 

When I press shortcut key, animation is starting, but when we press another key, animation wont stop (should be using stop key) and we cant change to other animation.

I want when we press a new key, we dont need to press "stop" key.
For now , the route is like this:
Press Key to Play > Press Stop to stop > Press another Key to play another animation
it should be
Press Key to Play > Press another key to stop and start other animation

Thanks before and sorry for bad english :D

**Comment by mchorse** [comment]
Ah, gotcha! It's a very nice suggestion, I'll add this in the next update 👍

**Comment by thenoobi** [comment]
hi thanks for your reply, I'l be waiting for next updates "emoticons" is best mod!!!

**Comment by mchorse** [comment]
Implemented, I'll publish the mod in few days. Thanks for suggestion! 🙂
